### ISSUE TITLE
Resfinder find no ARGs on HMD DB 

### ISSUE THREAD

**Issue by gameUser6398** [genomicepidemiology/resfinder#2]
![image](https://github.com/user-attachments/assets/ef97c618-07f4-48a1-a1f0-7a2a54272023)

HMD DB is from http://www.cbrc.kaust.edu.sa/[HMDARG](http://www.cbrc.kaust.edu.sa/HMDARG/)/

resfinder_db version: 2.4.0
resfinder version: 4.5.0

`python -m resfinder -ifa {inputfile} -o {save_dir} -db_res {db_path_res} --acquired`

**Comment by andrewpadawan** [comment]
Hello,
it looks like the database you have tried to use is encoded in aminoacid sequences. Resfinder only allows analysis of genetic sequences (ACGT and N bases). 

You may also be interested in our online webservice for Resfinder: http://genepi.food.dtu.dk/resfinder

**Comment by gameUser6398** [comment]
Thanks!
